services:
  flutter-app:
    build: .
    container_name: AH-MAPRICE-FA
    ports:
      - "8019:3000"
    volumes:
      - .:/app
    environment:
      - FLUTTER_ENV=production
    networks:
      - ag

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - ag

networks:
  ag:
    driver: bridge
    external: true 

