version: '3'
services:
  flutter-app:
    build: .
    ports:
      - "3000:3000" # Cambia los puertos según lo que necesites
    volumes:
      - .:/app
    environment:
      - FLUTTER_ENV=production
