server {
    listen 80;

    location / {
        root /app/build/web;  # Cambia a la ruta correcta de tu aplicación construida
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
